easy_admin:
    design:
        form_theme: # Both themes are for ckeditor integration
            - "@EasyAdmin/form/bootstrap_4.html.twig"
    entities:
        Page:
            class: App\Entity\Page
            form:
                fields:
                    - { property: 'title'}
                    - { property: 'parent'}
        Image:
            class: App\Entity\Image
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.page_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.page_images%' }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }